# Generated by Django 5.0.3 on 2024-03-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('s_name', models.CharField(max_length=20)),
                ('phone_no', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('ac', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=10)),
            ],
        ),
    ]
